Blogs.CMS/Controllers/TagController.cs
using AutoMapper;
using Blogs.CMS.Commons;
using Blogs.CMS.Controllers.Params;
using Blogs.CMS.Models;
using Blogs.CMS.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blogs.CMS.Controllers
{
    public class TagController : BaseController
    {
        private readonly TagService _tagService;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IMapper _mapper;

        public TagController(TagService tagService,
            IMapper mapper,
            CategoryService categoryService,
            IWebHostEnvironment hostEnvironment
            )
        {
            _tagService = tagService;
            _mapper = mapper;
            webHostEnvironment = hostEnvironment;
        }

        [HttpGet("tag")]
        public async Task<IActionResult> Index()
        {
            List<TagsGetModel> list = await _tagService.GetTags().Select(_ => new TagsGetModel
            {
                Title = _.Title,
                Slug = _.Slug,
                Id = _.Id
            }).ToListAsync();

            return View(list);
        }

        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddTagParams input)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var tagEntry = await _tagService.Add(input);
                    if (tagEntry is not null)
                    {
                        this.SetNotification("Tạo tag thành công", NotificationEnumeration.Success, true);
                    }
                    else
                    {
                        this.SetNotification("Tạo tag thành công", NotificationEnumeration.Error, true);
                    }
                }
            }
            catch (Exception e)
            {
                throw;
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var tag = await _tagService.GetTag(id);

            return PartialView(tag);
        }


        public async Task<IActionResult> Delete(int id)
        {
            var data = await _tagService.GetTag(id);

            var model = _mapper.Map<DeleteTagParams>(data);

            return PartialView(model);
        }
    }
}

Blogs.CMS/Views/Tag/Create.cshtml
@model Blogs.CMS.Controllers.Params.AddTagParams
@{

}
<div class="modal-content">
    <div class="modal-header border-bottom-0">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Tao Tag</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Hãy nhập đầy đủ các trường bắt buộc dưới đây.
                    </div>
                    <div class="panel-body">
                        @*@if (TempData["Notification"] != null)
                        {
                        @Html.Hidden("NotificationAutoHide", TempData["NotificationAutoHide"])
                        <div id="NotificationBox" class="@TempData["NotificationCSS"]" style="display: none">
                        @TempData["Notification"]
                        </div>
                        }*@
                        <div class="row">
                            <div class="col-lg-12">
                                @using (Html.BeginForm("Create", "Tag", FormMethod.Post, new { @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)

                                    <div class="form-group">
                                        <label>@Html.LabelFor(model => model.Title)</label>
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Title)
                                    </div>

                                    <div class="form-group">
                                        <label>@Html.LabelFor(model => model.Slug)</label>
                                        @Html.TextBoxFor(model => model.Slug, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Slug)
                                    </div>

                                    <button type="submit" class="btn btn-info btn-block btn-round">Tạo</button>
                                }
                            </div>
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#Title").blur(function () {
        var title = $("#Title").val().trim();
        
        //Đổi chữ hoa thành chữ thường
        var slug = title.toLowerCase();
 
        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@@' + slug + '@@';
        slug = slug.replace(/\@@\-|\-\@@|\@@/gi, '');

        $("#Slug").val(slug);
    });
</script>

Blogs.CMS/Views/Tag/Delete.cshtml
@model Blogs.CMS.Controllers.Params.DeleteTagParams
@{

}
<div class="modal-content">
    <div class="modal-header border-bottom-0">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Bạn có chắc muốn xóa tag này không?</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            @using (Html.BeginForm("Delete", "Tag", FormMethod.Post, new { @role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)
                                @Html.HiddenFor(model => model.Id)

                                <div class="col-lg-6">
                                    <button type="submit" class="btn btn-info btn-block btn-round">Xóa</button>
                                </div>
                                <div class="col-lg-6">
                                    <button type="button" class="btn btn-danger btn-block btn-round" data-dismiss="modal">Hủy</button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

</script>

Blogs.CMS/Views/Tag/Edit.cshtml
@model Blogs.CMS.Controllers.Params.EditTagParams
@{

}

<div class="modal-content">
    <div class="modal-header border-bottom-0">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Chỉnh sửa Tag</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Hãy nhập đầy đủ các trường bắt buộc dưới đây.
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @using (Html.BeginForm("Edit", "Tag", FormMethod.Post, new { @role = "form" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary(true)

                                    <div class="form-group">
                                        <label>@Html.LabelFor(model => model.Title)</label>
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Title)
                                    </div>

                                    <div class="form-group">
                                        <label>@Html.LabelFor(model => model.Slug)</label>
                                        @Html.TextBoxFor(model => model.Slug, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Slug)
                                    </div>

                                    <button type="submit" class="btn btn-info btn-block btn-round">Tạo</button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#Title").blur(function () {
        var title = $("#Title").val().trim();

        //Đổi chữ hoa thành chữ thường
        var slug = title.toLowerCase();

        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@@' + slug + '@@';
        slug = slug.replace(/\@@\-|\-\@@|\@@/gi, '');

        $("#Slug").val(slug);
    });
</script>

Blogs.CMS/Views/Tag/Index.cshtml
@model IEnumerable<Blogs.CMS.Models.TagsGetModel>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Danh sach danh muc</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <button type="button" class="btn btn-success" onclick="showCreateModal()" data-toggle="modal" data-target="#createModal">
                    Create
                </button>
            </div>
            <div class="panel-body">
                <span id="actionMessage"></span>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="thead-dark">
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var p in Model)
                            {
                                <tr>
                                    <td>@p.Id</td>
                                    <td>@p.Title</td>
                                    <td>
                                        <button type="button" class="btn btn-info" onclick="showEditTagModal(@p.Id)" data-toggle="modal" data-target="#createModal">
                                            Sửa
                                        </button>
                                        <button type="button" class="btn btn-danger" onclick="showDeleteTagModal(@p.Id)" data-toggle="modal" data-target="#createModal">
                                            Xóa
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@if ((string?)TempData["NotificationType"] == "success")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("@TempData["Notification"]", '', "success");
        };
    </script>
}
else if ((string?)TempData["NotificationType"] == "error")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Có gì đó sai sai", '', "error");
        };
    </script>
}
<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
    </div>
</div>

<script>

    function showCreateModal() {
        $.get('@Url.Action("Create", "Tag")', function (content) {
            $(".modal-dialog-centered").html(content)
        });
    }

    function showEditTagModal(id) {
        $.get('@Url.Action("Edit", "Tag")', { id: id }, function (content) {
            $(".modal-dialog-centered").html(content)
        });
    }

    function showDeleteTagModal(id) {
        $.get('@Url.Action("Delete", "Tag")', { id: id }, function (content) {
            $(".modal-dialog-centered").html(content)
        });
    }
</script>