Blogs.CMS/Controllers/BaseController.cs
using Blogs.CMS.Commons;
using Microsoft.AspNetCore.Mvc;

namespace Blogs.CMS.Controllers
{
    public class BaseController : Controller
    {
        public BaseController()
        {

        }

        public void SetNotification(string message, NotificationEnumeration notifyType, bool autoHideNotification = true)
        {
            TempData["Notification"] = message;
            //this.TempData["NotificationAutoHide"] = (autoHideNotification) ? "true" : "false";

            switch (notifyType)
            {
                case NotificationEnumeration.Success:
                    TempData["NotificationType"] = "success";
                    break;
                case NotificationEnumeration.Error:
                    TempData["NotificationType"] = "error";
                    break;
            }
        }
    }
}

Blogs.CMS/Views/Shared/_Layout.cshtml
@using Blogs.CMS.ViewComponents

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <link rel="icon" href="/favicon.ico">
    <title>Blog CMS</title>
    <!-- Core CSS - Include with every page -->

    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.8.24.min.js"></script>
    <link href="~/css/themes/admin/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/themes/admin/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <!-- Page-Level Plugin CSS - Dashboard -->
    <link href="~/css/themes/admin/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">
    <link href="~/css/themes/admin/css/plugins/timeline/timeline.css" rel="stylesheet">

    <!-- SB Admin CSS - Include with every page -->
    <link href="~/css/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/css/themes/admin/css/sb-admin.css" rel="stylesheet">
    <link href="~/css/themes/admin/css/custom.css" rel="stylesheet">
    <!-- Page-Level Plugin CSS - Tables -->
    <link href="~/css/themes/admin/css/plugins/dataTables/dataTables.bootstrap.css" rel="stylesheet">
    @*@Styles.Render("~/themes/admin/common");
    @Styles.Render("~/Content/themes/admin/dashboard");*@
    <!-- Core Scripts - Include with every page -->
    @*@Scripts.Render("~/bundles/adminjs")
    @Scripts.Render("~/bundles/dashboardjs")*@
    <!-- Core Scripts - Include with every page -->
    <link media="screen" rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.css" />
    <link media="screen" rel="stylesheet" href='https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.css' />

    <link rel="stylesheet prefetch" href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.js"></script>

    <script src="~/Scripts/admin/bootstrap.min.js"></script>
    <script src="~/Scripts/plugins/metisMenu/jquery.metisMenu.js"></script>
    <!-- SB Admin Scripts - Include with every page -->
    <script src="~/Scripts/admin/sb-admin.js"></script>
    <!-- Page-Level Plugin Scripts - Tables -->
    <script src="~/Scripts/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="~/Scripts/plugins/dataTables/dataTables.bootstrap.js"></script>
    <script src="~/Scripts/dialogmessage.js"></script>
    <script src="~/Scripts/Plugins/ckfinder/ckfinder.js" type="text/javascript"></script>
    <script src="~/Scripts/Plugins/ckeditor/ckeditor.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>

    <link href="~/select2/css/select2.min.css" rel="stylesheet" />
    <!-- select2-bootstrap4-theme -->
    <link href="https://raw.githack.com/ttskch/select2-bootstrap4-theme/master/dist/select2-bootstrap4.css" rel="stylesheet">
    <script src="~/select2/js/select2.js"></script>
    <script src="~/select2/js/select2.js"></script>

    <script>
        $(document).ready(function () {
            $('#dataTables').dataTable({
                "iDisplayLength": 10,
                "rowReorder": true,
                "oSearch": {
                    "sZeroRecords": "Không có bản ghi nào trong danh sách"
                }
            });
            //$("#NotificationBox").fadeIn(1000);

            //if ($("#NotificationAutoHide").val() == "true") {
            //    $("#NotificationBox").delay(1000).slideUp(500);
            //}

        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            //SetDialog();
            //$("#btnSelectImg").click(function () {
            //    var finder = new CKFinder();
            //    finder.selectActionFunction = function (fileUrl) {
            //        $('#txtImgUrl').val(fileUrl);
            //    };
            //    finder.popup();
            //});
            var editor = CKEDITOR.replace('contenteditor', {
                customConfig: '/Scripts/Plugins/ckeditor/article.js',
            });
            $("#datepicker").datepicker({ dateFormat: 'dd/mm/yy' });
        });

    </script>

</head>
<body>
    <div id="wrapper">
        @{
            Html.RenderPartial("_TopNavBar");
        }
        @*
        <partial name="_TopNavBar" />*@
        <!-- /.navbar-static-top -->
        <!-- /.navbar-static-top -->
        @await Component.InvokeAsync(typeof(MenuViewComponents));

        <!-- /.navbar-static-side -->

        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->


</body>
</html>

Blogs.CMS/Views/Shared/_MainMenu.cshtml
@model IEnumerable<Blogs.CMS.Models.FunctionViewModel>
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    @*<input type="text" class="form-control" placeholder="@Nes.Resources.NesResource.AdminHomeSearchText">*@
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                @*<a href="/home/index"><i class="fa fa-dashboard fa-fw"></i>@Nes.Resources.NesResource.AdminHomeMenuText</a>*@
                <a href="/home/index"><i class="fa fa-dashboard fa-fw"></i>Trang Chu</a>
            </li>
            @foreach (var item in Model)
            {
                <li>
                    @{
                        var arrowCss = item.Children.Count > 0 ? "fa arrow" : "";
                    }
                    <a href="@item.SLug" target="@item.Target"><i class="@item.CssClass"></i> @item.Text<span class="@arrowCss"></span></a>
                    @if (item.Children.Count > 0)
                    {
                        <ul class="nav nav-second-level">
                            @foreach (var child in item.Children)
                            {
                                <li>
                                    <a href="@child.SLug" target="@child.Target">@child.Text</a>
                                </li>
                            }
                        </ul>
                    }
                </li>
            }

        </ul>
    </div>
</nav>

Blogs.CMS/Views/Shared/_TopNavBar.cshtml
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/Home/Index">@ViewBag.SystemNameText</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li>

            @*@if (Request.IsAuthenticated)
            {
            @Html.ActionLink(User.Identity.Name, "Home", "Index");
            }*@
        </li>
        <li>
            <a href="/">Trang client</a>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                @*<li>

                @Html.ActionLink(@Nes.Resources.NesResource.AdminMasterLogoutText, "Logout", "Account");
                </li>*@
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
        <li>
            @*@using (Html.BeginForm("ChangeCulture", "Base", FormMethod.Post))
            {
            @Html.Hidden("returnUrl", Request.Url.AbsoluteUri)
            @Html.DropDownList("language", (SelectList)ViewBag.Languages, new { @onchange = "this.form.submit();" })
            } *@
            @*<select id="language">
            <option value="vn">Vietnamese</option>
            <option value="en">English</option>
            </select>*@
        </li>
    </ul>
    <!-- /.navbar-top-links -->

</nav>